[package]
name = "tgba-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambassador = "0.3.0"
anyhow = "1.0.57"
bitvec = "1.0.0"
log = "0.4.16"
