[workspace]
members = ["tgba-core"]

[package]
name = "tgba"
version = "0.1.0"
edition = "2021"

[dependencies]
tgba-core = { path = "tgba-core" }
anyhow = "1.0.57"
argopt = "0.3.0"
compress-tools = "0.12.2"
env_logger = "0.9.0"
log = "0.4.16"
prettytable-rs = "0.8.0"
tempfile = "3.3.0"
